site_name: LB1161 - Sovereign Cloud Architecture with OpenShift, Multi-Cluster Data
  Residency and Compliance Management
docs_dir: publishing-house/spec
nav:
- Home: index.md
- Design Spec: design.md
- Modules:
  - Module 1 - Operations And Security: modules/module-01-operations-and-security.md
  - Module 2 - Assurance: modules/module-02-assurance.md
  - Module 3 - Technology And Supply Chain: modules/module-03-technology-and-supply-chain.md
  - Module 4 - Data And Ai: modules/module-04-data-and-ai.md
  - Module 5 - Supplementary Governance: modules/module-05-supplementary-governance.md
plugins:
- techdocs-core
